package com.fivechess.chessboard;

public enum ChessConnType {
    NOTHING,
    LONG_CONNECTION,
    SUCCESSIVE_FIVE,
    ALIVE_FOUR, SPUR_FOUR, DIE_FOUR,
    SUCCESSIVE_ALIVE_THREE, SKIP_ACTIVE_THREE, DIE_THREE,
    SUCCESSIVE_ALIVE_TWO, SKIP_ALIVE_TWO, DIE_TWO
}
