package com.fivechess.chessboard;

public enum ChessConnectionType {
    NOTHING,
    SUCCESSIVE_ALIVE_TWO, SKIP_ALIVE_TWO, ADVANCED_SKIP_ALIVE_TWO, SLEEP_TWO, DIE_TWO,
    SUCCESSIVE_ALIVE_THREE, SKIP_ALIVE_THREE, SLEEP_THREE, DIE_THREE,
    ALIVE_FOUR, SPUR_FOUR, DIE_FOUR,
    SUCCESSIVE_FIVE,
    SUCCESSIVE_LONG
}
